AckslD/nvim-neoclip.lua

README.md, doc/neoclip.txt, lua/neoclip.lua, lua/neoclip/db.lua, lua/neoclip/fzf.lua, lua/neoclip/handlers.lua, lua/neoclip/settings.lua, lua/neoclip/storage.lua, lua/neoclip/telescope.lua, lua/neoclip/warn.lua, lua/telescope/_extensions/macroscope.lua
`neoclip` can now also keep track of recorded macros (opt-out) and be accessed with the `macroscope` extension:
```vim
:Telescope macroscope
```
requires [`RecordingLeave`](https://github.com/neovim/neovim/pull/16684) to work.
=> Macroscope

.github/workflows/ci.yml
1. We don't need to restrict the branch to run CI.
2. `workflow_dispatch` enables us to manually trigger CI.
3. A daily scheduled run can catch dependencies' breaking changes.
=> ci: better triggers

README.md
the example configs are invalid syntax without those commas
=> add missing `,` in README

lua/neoclip/fzf.lua, lua/neoclip/telescope.lua
Hello, wanting to provide a fix for #66 that will allow users to disable mappings by passing false.
```lua
require(‘neoclip’).setup({
keys = {
telescope = {
i = {
paste = false — will restore telescope default <c-p> action to move to prev item
}
}
}
})
```
=> Resolve #66 by allowing users to disable mappings by passing false

lua/neoclip/fzf.lua
This makes fzf-lua work again with neoclip, using the new API also supports using `:FzfLua resume` to respawn fzf-lua's neoclip UI.
=> fix(fzf-lua): use the newer 'fzf_exec' API

README.md, lua/neoclip/fzf.lua, lua/neoclip/telescope.lua
This change addresses issue #83. Now one can setup neoclip and override the prompt variable, for example, with the following configuration:
```lua
require('neoclip').setup {
keys = {
fzf = {
opts = {
prompt = 'clip> '
}
}
}
}
```
=> feat(fzf-lua): option to override fzf-lua picker opts

README.md, lua/neoclip/telescope.lua
fixes #89.
Simply pass down the `typ` variable to the telescope custom action handler
=> feat: on telescope custom action, add property to distinguish between a yank and a macro entry

README.md, lua/neoclip/fzf.lua, lua/neoclip/settings.lua, lua/neoclip/storage.lua, lua/neoclip/telescope.lua
Closes #85.
This is a feature I was also interested in, so I decided to try a simple implementation.
This will add a new boolean option `refresh_entry_on_select` (default = false), which when set, will make whichever entry the user selects on telescope/fzf as the most recent.
One thing I disliked about this is the name of the option `refresh_entry_on_select`. Do you have a better suggestion?
Before selecting A:
After selecting A, and reopening telescope:
=> feat: when using telescope/fzf, add option to set the selected entry as most recent

lua/neoclip/fzf.lua
Recent changes in fzf-lua add preview buffer caching which breaks accessing the preview buffer directly, this PR makes the necessary adjustments and also improves the fzf-lua experience to flicker free scrolling.
=> fix: fzf-lua preview caching update

README.md, lua/neoclip/settings.lua, lua/neoclip/sorted_set.lua, lua/neoclip/storage.lua, lua/neoclip/telescope.lua, lua/neoclip/utils.lua, tests/plenary/neoclip_spec.lua, tests/plenary/sorted_set_spec.lua
Closes #91.
This allows the user to edit an entry in telescope. To edit an entry, you have to open telescope, use the edit mapping (default <C-e> in insert mode), edit the new buffer however you want, then close the buffer (`:q`) to save the changes. Here are some screenshots:
- Open telescope: ![image](https://user-images.githubusercontent.com/26410371/212742692-9a52ca83-4f4f-43ce-aec0-a3379373f2fa.png)
- Press <C-e> in insert mode: ![image](https://user-images.githubusercontent.com/26410371/212742733-a0db01ce-66de-4330-9e61-8d1ac17bf648.png)
- Change the buffer contents: ![image](https://user-images.githubusercontent.com/26410371/212742796-625fcc9e-c541-4ccb-b890-71d2ed293696.png)
- Exit the new buffer (`:q`):  ![image](https://user-images.githubusercontent.com/26410371/212742855-6eb662d …
=> feat: allow to edit and entry

README.md, lua/neoclip/settings.lua, lua/neoclip/telescope.lua, tests/plenary/neoclip_spec.lua
This would resolve [this](https://github.com/AckslD/nvim-neoclip.lua/blob/6617f6cf8422be01eb5673e165ca20bc5c048085/lua/neoclip/telescope.lua#L61) and [this](https://github.com/AckslD/nvim-neoclip.lua/blob/6617f6cf8422be01eb5673e165ca20bc5c048085/lua/neoclip/telescope.lua#L77) todos.
It adds a new settings at `on_select`, `on_paste` and `on_replay` called `close_telescope` (defaults to true), which when set to true, will close telescope after the action. If set to false, the action will be executed while maintaining the telescope window open.
=> feat: closing telescope after action is now optional

README.md, lua/neoclip/settings.lua, lua/neoclip/telescope.lua, tests/plenary/neoclip_spec.lua
Closes #98.
Macros will now be shown as a proper string that can be used in a `map`,
instead of showing the raw byte representation of the keycodes.
An example: what would be previously shown as "one\ntwo" will now be
shown as "one<CR>two"
A new options `disable_keycodes_parsing` was added that if set to `true` (dafault `false`), will disable this feature, and revert to the old behavior
This option will only change how macros are displayed, and not how they are stored.
Here's a usage example:
- Here's a macro: ![image](https://user-images.githubusercontent.com/26410371/212791534-ae08c3ea-cbb0-48cc-b97b-5695a75ab532.png)
- Editing the macro (pressed `<C-E>`): ![image](https://user-images.githubusercontent.com/26410371/212791571-3ada49c1-3f41-4183-a8da-ba7f9d1b5f72.png)
- After editing the …
=> feat: display macros as map keycodes instead of raw bytes

lua/neoclip/handlers.lua
Fixes #109
Sadly regcontents don't exist when copying from nvim-tree the event is `vim.empty_dict()` so for now it's best to return from `should_add` to suppress the error. 
Before - yanking from nvim-tree:
After (no errors, value is added to register but not neoclip - which was like this all the time it's just not showing the annoying error that has to be acknowledged every time):
=> fix: event without regcontents

setup.lua.example
Add example file for activate.nvim
activate.nvim is a plugin that can be used to install and setup plugins directly inside neovim.
https://github.com/roobert/activate.nvim
=> add example file for activate.nvim

lua/neoclip/fzf.lua
The delemiter was set incorrectly and could not retrieve the content to display.
=> fix(fzf-lua): items are displayed as blank

lua/neoclip/fzf.lua
This commit fixes the following error message:
```
[Fzf-lua] `fzf_opts` are automatically shellescaped. Please remove surrounding quotes from --header='Pick new entry for registers "'
```
This PR closes #136
=> fix(fzf-lua): remove unnecessary shellescape in fzf_opts

lua/neoclip/fzf.lua
`FzfWin:update_scrollbar()` was changed to `FzfWin:update_preview_scroolbar()` in ibhagwan/fzf-lua@fc70792718d4a41101956c10ec04b6bf6a258777
It will make an error when using fzf-lua picker `:lua require('neoclip.fzf')()`
```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/nvim-neoclip.lua/lua/neoclip/fzf.lua:102: attempt to call method 'update_scrollbar' (a nil value)
```
=> fix(fzf-lua): update update_scrollbar() to update_preview_scroolbar()

README.md, lua/neoclip/settings.lua, lua/neoclip/telescope.lua
Add initial_mode to settings to control the prompt's initial mode.  Addresses #139
=> Add initial_mode to settings

lua/neoclip/fzf.lua
Explicitly set `git_icons = false` and `file_icons = false`  to avoid StackOverflow.
Fixes https://github.com/AckslD/nvim-neoclip.lua/issues/143
=> fix(fzf-lua): stackoverflow when git_icons=true

README.md, lua/neoclip/picker_utils.lua, lua/neoclip/settings.lua, lua/neoclip/telescope.lua
See #117 
Adds a dedent_picker_display setting, which if true will cause the picker items to have leading whitespace trimmed.
=> Add dedent_picker_display setting
